"""feature_schema.py — AUTO-GENERATED from 'Data Ingestion.ipynb' (cell 15).

The exact ordered input signature of the Databricks-hosted
workspace.dataattproject.health_food_risk_detector Spark ML pipeline.

These are the 106 numeric feature columns selected in the notebook: every
numeric column of health_food_augmented_labeled EXCEPT the label/derived
columns and the BMI + blood-pressure leakage columns. The pipeline median-
imputes missing values, so columns the platform cannot source (labs, income,
waist, calories, caffeine) are sent as null and filled in at inference time.

Do not edit by hand — regenerate from the notebook if the model is retrained.
"""

FEATURE_ORDER = [
    'gender',
    'age',
    'race_ethnicity',
    'education_level',
    'income_to_poverty_ratio',
    'weight_kg',
    'height_cm',
    'waist_cm',
    'calories',
    'protein_g',
    'carbs_g',
    'sugar_g',
    'fiber_g',
    'total_fat_g',
    'saturated_fat_g',
    'cholesterol_mg',
    'sodium_mg',
    'caffeine_mg',
    'medication_count',
    'lab_URXUMA',
    'lab_URXUMS',
    'lab_URXUCR_x',
    'lab_URXCRS',
    'lab_URDACT',
    'lab_LBXSAL',
    'lab_LBDSALSI',
    'lab_LBXSAPSI',
    'lab_LBXSASSI',
    'lab_LBXSATSI',
    'lab_LBXSBU',
    'lab_LBDSBUSI',
    'lab_LBXSC3SI',
    'lab_LBXSCA',
    'lab_LBDSCASI',
    'lab_LBXSCH',
    'lab_LBDSCHSI',
    'lab_LBXSCK',
    'lab_LBXSCLSI',
    'lab_LBXSCR',
    'lab_LBDSCRSI',
    'lab_LBXSGB',
    'lab_LBDSGBSI',
    'lab_LBXSGL',
    'lab_LBDSGLSI',
    'lab_LBXSGTSI',
    'lab_LBXSIR',
    'lab_LBDSIRSI',
    'lab_LBXSKSI',
    'lab_LBXSLDSI',
    'lab_LBXSNASI',
    'lab_LBXSOSSI',
    'lab_LBXSPH',
    'lab_LBDSPHSI',
    'lab_LBXSTB',
    'lab_LBDSTBSI',
    'lab_LBXSTP',
    'lab_LBDSTPSI',
    'lab_LBXSTR',
    'lab_LBDSTRSI',
    'lab_LBXSUA',
    'lab_LBDSUASI',
    'lab_LBXWBCSI',
    'lab_LBXLYPCT',
    'lab_LBXMOPCT',
    'lab_LBXNEPCT',
    'lab_LBXEOPCT',
    'lab_LBXBAPCT',
    'lab_LBDLYMNO',
    'lab_LBDMONO',
    'lab_LBDNENO',
    'lab_LBDEONO',
    'lab_LBDBANO',
    'lab_LBXRBCSI',
    'lab_LBXHGB',
    'lab_LBXHCT',
    'lab_LBXMCVSI',
    'lab_LBXMCHSI',
    'lab_LBXMC',
    'lab_LBXRDW',
    'lab_LBXPLTSI',
    'lab_LBXMPSI',
    'lab_PHQ020',
    'lab_PHQ030',
    'lab_PHQ040',
    'lab_PHQ050',
    'lab_PHQ060',
    'lab_PHAFSTHR_x',
    'lab_PHAFSTMN_x',
    'lab_PHDSESN',
    'lab_LBDHDD',
    'lab_LBDHDDSI',
    'lab_LBXHA',
    'lab_LBXHBS',
    'lab_LBXHBC',
    'lab_LBDHBG',
    'lab_LBDHD',
    'lab_LBDHEG',
    'lab_LBDHEM',
    'lab_LBXGH',
    'lab_WTSH2YR_x',
    'lab_LBXTC',
    'lab_LBDTCSI',
    'lab_LBXTTG',
    'lab_WTSH2YR_y',
    'lab_URXVOL1',
    'lab_URDFLOW1',
]

assert len(FEATURE_ORDER) == 106
